<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>OpenAI 开发者论坛 - 最新帖子</title>
    <link>https://community.openai.com</link>
    <description>最新帖子</description>
    <lastBuildDate>Tue, 23 Jan 2024 21:17:37 GMT</lastBuildDate>
    <item>
      <title>ChatGPT (GPT-4) 无法使用，因为“我们的系统检测到您的系统存在异常活动。请稍后重试。”</title>
      <link>https://community.openai.com/t/chatgpt-gpt-4-unusable-due-to-our-systems-have-detected-unusual-activity-from-your-system-please-try-again-later/557407#post_19</link>
      <description><![CDATA[我遇到了这个错误。关闭远程桌面软件后，就没有遇到这个错误了。所以，如果你遇到这个错误，你应该尝试关闭一些正在运行的软件。（原谅我糟糕的英语）]]></description>
      <guid>https://community.openai.com/t/chatgpt-gpt-4-unusable-due-to-our-systems-have-detected-unusual-activity-from-your-system-please-try-again-later/557407#post_19</guid>
      <pubDate>Tue, 23 Jan 2024 21:14:30 GMT</pubDate>
    </item>
    <item>
      <title>AttributeError：模块“pydantic”没有属性“BaseModel”</title>
      <link>https://community.openai.com/t/attributeerror-module-pydantic-has-no-attribute-basemodel/599003#post_5</link>
      <description><![CDATA[


拉维特贾：
&lt;块引用&gt;
蟒蛇蜘蛛


升级依赖项和要求...
https： //docs.spyder-ide.org/current/troubleshooting/basic-first-aid.html]]></description>
      <guid>https://community.openai.com/t/attributeerror-module-pydantic-has-no-attribute-basemodel/599003#post_5</guid>
      <pubDate>Tue, 23 Jan 2024 21:14:26 GMT</pubDate>
    </item>
    <item>
      <title>助理 API 的替代方案</title>
      <link>https://community.openai.com/t/alternatives-to-assistant-api/589772#post_9</link>
      <description><![CDATA[嗯……这是个好主意……
急于用 LangChain 文档创建一个助手。只需要一些纸板、一支记号笔，我就可以开始做生意了。]]></description>
      <guid>https://community.openai.com/t/alternatives-to-assistant-api/589772#post_9</guid>
      <pubDate>Tue, 23 Jan 2024 21:13:24 GMT</pubDate>
    </item>
    <item>
      <title>GPT 3.5 和 GPT 4 Turbo 1106 输出上下文长度问题</title>
      <link>https://community.openai.com/t/gpt-3-5-and-gpt-4-turbo-1106-question-for-output-context-length/598903#post_3</link>
      <description><![CDATA[但在某些用例中，我们需要更大的输出，而这些输出一直运行良好，例如您正在生成一个包含 30-40 个步骤的测试脚本，这不适用于 4k 代币限制。如果它与一个功能相关，我不能告诉最终用户将其划分为多个测试脚本，这只是一个示例。
我们构建的用例证明了我们的效率很高，并且只有 4k 代币限制并不会削减它，我希望它们为使用 EnterPrise GPT 的人们提供更大的输出上下文，我认为许多其他人可能必须改变他们的如果他们不使用具有某种分块和整理功能的 Assistant API，则可以实现。]]></description>
      <guid>https://community.openai.com/t/gpt-3-5-and-gpt-4-turbo-1106-question-for-output-context-length/598903#post_3</guid>
      <pubDate>Tue, 23 Jan 2024 21:12:54 GMT</pubDate>
    </item>
    <item>
      <title>AttributeError：模块“pydantic”没有属性“BaseModel”</title>
      <link>https://community.openai.com/t/attributeerror-module-pydantic-has-no-attribute-basemodel/599003#post_4</link>
      <description><![CDATA[现在我应该做什么来解决这个“AttributeError”？]]></description>
      <guid>https://community.openai.com/t/attributeerror-module-pydantic-has-no-attribute-basemodel/599003#post_4</guid>
      <pubDate>Tue, 23 Jan 2024 21:11:59 GMT</pubDate>
    </item>
    <item>
      <title>ChatGPT (GPT-4) 无法使用，因为“我们的系统检测到您的系统存在异常活动。请稍后重试。”</title>
      <link>https://community.openai.com/t/chatgpt-gpt-4-unusable-due-to-our-systems-have-detected-unusual-activity-from-your-system-please-try-again-later/557407#post_18</link>
      <description><![CDATA[我遇到了这个错误。关闭远程桌面软件后，就没有遇到这个错误了。所以，如果你遇到这个错误，你应该尝试关闭一些正在运行的软件。（原谅我糟糕的英语）]]></description>
      <guid>https://community.openai.com/t/chatgpt-gpt-4-unusable-due-to-our-systems-have-detected-unusual-activity-from-your-system-please-try-again-later/557407#post_18</guid>
      <pubDate>Tue, 23 Jan 2024 21:11:05 GMT</pubDate>
    </item>
    <item>
      <title>AttributeError：模块“pydantic”没有属性“BaseModel”</title>
      <link>https://community.openai.com/t/attributeerror-module-pydantic-has-no-attribute-basemodel/599003#post_3</link>
      <description><![CDATA[来自实际程序执行（anaconda Spyder）]]></description>
      <guid>https://community.openai.com/t/attributeerror-module-pydantic-has-no-attribute-basemodel/599003#post_3</guid>
      <pubDate>Tue, 23 Jan 2024 21:11:00 GMT</pubDate>
    </item>
    <item>
      <title>Gpt-4-1106-preview 搞乱了函数调用参数编码</title>
      <link>https://community.openai.com/t/gpt-4-1106-preview-messes-up-function-call-parameters-encoding/478500?page=5#post_96</link>
      <description><![CDATA[只是想提供我的解决方案，效果很好（在我的例子中，有一些非拉丁字符）：
创建工具(
CHANGE_ADDRESS_ORDER, &quot;更改订单地址，用 AA 表示 å，OE 表示 ø，AE 表示 æ。
所以基本上只是要求它将特殊字符映射到真实文本中不会出现的大写字母序列，然后进行简单的替换。]]></description>
      <guid>https://community.openai.com/t/gpt-4-1106-preview-messes-up-function-call-parameters-encoding/478500?page=5#post_96</guid>
      <pubDate>Tue, 23 Jan 2024 21:10:12 GMT</pubDate>
    </item>
    <item>
      <title>您已达到 GPT-4、WTH 的当前使用上限</title>
      <link>https://community.openai.com/t/youve-reached-the-current-usage-cap-for-gpt-4-wth/598606#post_16</link>
      <description><![CDATA[OpenAI已多次调整使用上限。希望很快会再次增加 。他们发布了很多新东西，最终消耗了更多资源]]></description>
      <guid>https://community.openai.com/t/youve-reached-the-current-usage-cap-for-gpt-4-wth/598606#post_16</guid>
      <pubDate>Tue, 23 Jan 2024 21:09:43 GMT</pubDate>
    </item>
    <item>
      <title>您已达到 GPT-4、WTH 的当前使用上限</title>
      <link>https://community.openai.com/t/youve-reached-the-current-usage-cap-for-gpt-4-wth/598606#post_15</link>
      <description><![CDATA[这并不是当一个人为 GPT4 付费时应该发生的事情的重点......]]></description>
      <guid>https://community.openai.com/t/youve-reached-the-current-usage-cap-for-gpt-4-wth/598606#post_15</guid>
      <pubDate>Tue, 23 Jan 2024 21:08:46 GMT</pubDate>
    </item>
    <item>
      <title>Bing Dall-E 3 与 ChatGPT Plus Dall-E 3 商业用途</title>
      <link>https://community.openai.com/t/bing-dall-e-3-vs-chatgpt-plus-dall-e-3-commercial-use/598716#post_2</link>
      <description><![CDATA[


 lompfilm：
&lt;块引用&gt;
我可以合法地将 ChatGPT Plus 创建的图形用于商业用途（例如作为游戏中卡片上的插图）吗？


是的，您通过 API 或 ChatGPT+ 创建的所有图像均归您所有。



 lompfilm：
&lt;块引用&gt;
我也可以以同样的方式将 Bing 生成的图形用于商业用途吗？


不，Bing 保留您使用 Bing 生成的所有图像的所有权利。]]></description>
      <guid>https://community.openai.com/t/bing-dall-e-3-vs-chatgpt-plus-dall-e-3-commercial-use/598716#post_2</guid>
      <pubDate>Tue, 23 Jan 2024 21:08:45 GMT</pubDate>
    </item>
    <item>
      <title>您已达到 GPT-4、WTH 的当前使用上限</title>
      <link>https://community.openai.com/t/youve-reached-the-current-usage-cap-for-gpt-4-wth/598606#post_14</link>
      <description><![CDATA[100/3 仍然不可行。 250/3 就不错了。最低限度为 200/3。为 Enterprise 付费超出了我的能力范围。我希望这个问题能够得到解决……因为 GPT4、CustomGPT 和插件都非常棒，但是为无法使用的出色产品付费是没有意义的。]]></description>
      <guid>https://community.openai.com/t/youve-reached-the-current-usage-cap-for-gpt-4-wth/598606#post_14</guid>
      <pubDate>Tue, 23 Jan 2024 21:07:39 GMT</pubDate>
    </item>
    <item>
      <title>AttributeError：模块“pydantic”没有属性“BaseModel”</title>
      <link>https://community.openai.com/t/attributeerror-module-pydantic-has-no-attribute-basemodel/599003#post_2</link>
      <description><![CDATA[这几乎肯定是一个依赖性问题。
您需要确保路径变量正确，并针对当前用户安装的 Conda 进行升级，以在同一执行环境中获取所有支持库。
最新 OpenAI Python 模块的依赖转储
已满足要求：anyio&lt;5,&gt;=3.5.0
 在 c:\program files\python311\lib\site-packages (来自 openai) (3.7.1)
已满足要求：distro&lt;2,&gt;=1.7.0
 在 c:\program files\python311\lib\site-packages (来自 openai) (1.8.0)
已满足要求：httpx&lt;1,&gt;=0.23.0
 在 c:\program files\python311\lib\site-packages (来自 openai) (0.25.1)
已满足要求：pydantic&lt;3,&gt;=1.9.0
 在 c:\program files\python311\lib\site-packages (来自 openai) (2.5.2)
已满足的要求：sniffio
 在 c:\program files\python311\lib\site-packages (来自 openai) (1.3.0)
已满足要求：tqdm&gt;4
 在 c:\program files\python311\lib\site-packages (来自 openai) (4.66.1)
已满足要求：typing-extensions&lt;5,&gt;=4.7
 在 c:\program files\python311\lib\site-packages (来自 openai) (4.8.0)
已满足要求：idna&gt;=2.8
 在 c:\program files\python311\lib\site-packages 中（来自anyio&lt;5,&gt;=3.5.0-&gt;openai）(3.4)
已满足的要求：证书
 在 c:\program files\python311\lib\site-packages (来自 httpx&lt;1,&gt;=0.23.0-&gt;openai) (2023.7.22)
已满足要求：httpcore
 在 c:\program files\python311\lib\site-packages 中（来自 httpx&lt;1,&gt;=0.23.0-&gt;openai）(1.0.2)
已满足要求：annotated-types&gt;=0.4.0
 在 c:\program files\python311\lib\site-packages 中（来自 pydantic&lt;3,&gt;=1.9.0-&gt;openai）(0.6.0)
已满足要求：pydantic-core==2.14.5
 在 c:\program files\python311\lib\site-packages 中（来自 pydantic&lt;3,&gt;=1.9.0-&gt;openai）(2.14.5)
已满足的要求：colorama
 在 c:\program files\python311\lib\site-packages 中（来自 tqdm&gt;4-&gt;openai）(0.4.6)
已满足要求：h11&lt;0.15，&gt;=0.13
 在 c:\program files\python311\lib\site-packages 中（来自 httpcore-&gt;httpx&lt;1,&gt;=0.23.0-&gt;openai）(0.14.0)

这是来自实际的程序执行，还是来自 IDE linter 或类型检查器？]]></description>
      <guid>https://community.openai.com/t/attributeerror-module-pydantic-has-no-attribute-basemodel/599003#post_2</guid>
      <pubDate>Tue, 23 Jan 2024 21:01:24 GMT</pubDate>
    </item>
    <item>
      <title>手动喂料数据对比。用数据训练模型</title>
      <link>https://community.openai.com/t/manual-feeding-data-vs-training-the-model-with-data/598976#post_2</link>
      <description><![CDATA[您好，欢迎来到社区！
通过“手动提供数据”，我假设您的意思是“在对话中向 GPT 提供信息”？
所以，如果我们以一种简单的方式来分解它，我们就会明白人工智能是算法和数学公式的一大堆。
当你与人工智能交谈时，你会认为它就像“运行”算法，让它基本上运转起来。 当您使用算法时，算法不会发生任何变化。当对话变得更大时，您只需增加放入算法中的变量的大小。
当您训练模型或对其进行微调时，您就是在以特定方式更改算法。训练/微调这些模型是改变所谓模型权重的方法。虽然我们无法准确理解这些权重的工作原理，但它们却影响了其输出。因此，如果您觉得需要调整实际算法以针对特定任务进行优化，那么微调非常适合。
这只是一个基本的介绍，但这仍然应该帮助您理解正在发生的事情 。我希望这能为您澄清一些事情！]]></description>
      <guid>https://community.openai.com/t/manual-feeding-data-vs-training-the-model-with-data/598976#post_2</guid>
      <pubDate>Tue, 23 Jan 2024 21:00:14 GMT</pubDate>
    </item>
    <item>
      <title>我正在 ChatGpt 的帮助下创建一个在线开发人员工具包应用程序，需要帮助来决定要实施哪些工具</title>
      <link>https://community.openai.com/t/im-creating-an-online-developer-toolkit-app-with-chatgpt-help-need-help-deciding-which-tools-to-implement/598934#post_2</link>
      <description><![CDATA[听起来很酷，您介意分享您网站的链接吗？]]></description>
      <guid>https://community.openai.com/t/im-creating-an-online-developer-toolkit-app-with-chatgpt-help-need-help-deciding-which-tools-to-implement/598934#post_2</guid>
      <pubDate>Tue, 23 Jan 2024 20:57:15 GMT</pubDate>
    </item>
    </channel>
</rss>