<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>OpenAI 开发者论坛 - 最新帖子</title>
    <link>https://community.openai.com</link>
    <description>最新帖子</description>
    <lastBuildDate>Wed, 03 Jan 2024 15:19:22 GMT</lastBuildDate>
    <item>
      <title>无需任何询问即可参与 ChatGPT</title>
      <link>https://community.openai.com/t/engage-with-chatgpt-without-any-inquiry/578181#post_2</link>
      <description><![CDATA[为了证实这一点，这是我所看到的
第一次 Hello 和空重试会创建一条预期消息。
在第三个提示中尝试“Hello”，但第四个提示为空。
&lt;小时/&gt;
您可以通过提供描述您要创建的图像的文本提示来使用 DALL·E 工具。以下是您可以如何构建对 DALL·E 工具的请求：

尺寸：指定所需图像的尺寸，无论是正方形 (1024x1024)、宽幅 (1792x1024) 还是全身肖像 (1024x1792)。
图像数量：决定要生成的图像数量，默认值通常为一张。
提示：写下您要创建的图像的详细说明。尽可能具体以获得最佳结果。
参考图片：如果您提出与上一张图片相关的请求，请包含该图片的参考 ID。

以下是如何调用 DALL·E 工具的示例：
{
  “尺寸”：“1024x1024”，
  “n”：1，
  “prompt”：“黄昏时紫色天空下的未来城市景观，有飞行汽车、霓虹灯和街上行走的不同人群。”
}

此请求将根据提供的详细描述生成一张方形图像。
&lt;小时/&gt;
我的猜测是，虽然您可能认为提示的初始标记是空列表，但它可能是 Hello 后跟一些退格键。
拥有权重会很有用。您是否尝试过使用权重公开的 GPT-2 进行相同的操作？]]></description>
      <guid>https://community.openai.com/t/engage-with-chatgpt-without-any-inquiry/578181#post_2</guid>
      <pubDate>Wed, 03 Jan 2024 15:13:32 GMT</pubDate>
    </item>
    <item>
      <title>RateLimitError：使用 gpt-4 和 gpt-3.5-turbo 时为 429</title>
      <link>https://community.openai.com/t/ratelimiterror-429-with-gpt-4-and-gpt-3-5-turbo/578186#post_1</link>
      <description><![CDATA[我是付费客户，并且使用的是旧版本的 OpenAI (openai-0.28.0)。我遇到了 Ratelimiterror 问题：
RateLimitError：您超出了当前配额，请检查您的计划和账单详细信息。有关此错误的更多信息，请阅读文档： https:// platform.openai.com/docs/guides/error-codes/api-errors。
我使用了在线提供的所有建议，并查看了模型限制和错误处理页面。我找到了一个用于验证错误代码的代码片段，这是输出：
openai.RateLimitError：错误代码：429 - {‘error’：{‘message’：‘您超出了当前配额，请检查您的计划和账单详细信息。有关此错误的更多信息，请阅读文档：https://platform.openai.com/docs/guides/error-codes/api-errors.&#39;, &#39;type&#39;: &#39;insufficient_quota&#39;, &#39;param&#39;: None, &#39;code&#39;: &#39;insufficient_quota&#39;}}
12 月 29 日之前一切都正常，但是到了 31 日，当我运行代码时，它开始抛出错误，现在已经 4 天了。
我又向我的账户添加了 10 美元，以防 9 美元的可用信用额度不够，但即便如此也没有解决问题。我以尽可能简单的形式使用 API（我从 OpenAI 网站获取了代码）。我已经尝试了一切，但似乎没有任何效果。有人可以帮我吗？我想我可以创建一个新帐户，但我会失去价值 20 美元的信用。
非常感谢！]]></description>
      <guid>https://community.openai.com/t/ratelimiterror-429-with-gpt-4-and-gpt-3-5-turbo/578186#post_1</guid>
      <pubDate>Wed, 03 Jan 2024 15:11:06 GMT</pubDate>
    </item>
    <item>
      <title>无法访问高级数据分析</title>
      <link>https://community.openai.com/t/unable-to-access-advanced-data-analysis/392125#post_15</link>
      <description><![CDATA[在默认的GPT-4中，通过仅选择模型选择器（您也可以选择 GPT-3.5），所有工具均已启用。其中包括高级数据分析，可以编写 Python 代码并在沙箱中运行它以执行计算或处理附加文件。
启用所有工具、浏览、dalle 和代码解释器（重命名为高级数据分析，或简称“分析”）后，AI 会预先加载文本，告诉它所有这些工具如何操作。这可能会分散它对作为基于代码的问题解决者的使命的注意力。
GPT 构建器允许设计者在制作 GPT 代理时打开和关闭每个工具。 OpenAI 在“探索”下自己制作了一些 GPT，在那里他们关闭了除您想要的单个工具之外的所有其他工具。
代码解释器不再有“测试版功能”或切换开关。]]></description>
      <guid>https://community.openai.com/t/unable-to-access-advanced-data-analysis/392125#post_15</guid>
      <pubDate>Wed, 03 Jan 2024 15:10:10 GMT</pubDate>
    </item>
    <item>
      <title>我给 gpt4-vision 提供 5 张图像，需要识别 2 张相似的图像？</title>
      <link>https://community.openai.com/t/i-give-5-images-to-gpt4-vision-and-need-to-identify-2-similar-images/546521#post_8</link>
      <description><![CDATA[您可以让 AI 通过您提供的 JSON 中的索引来识别图像。根据我的经验，它在最多 5-6 个图像时效果很好，但之后它就会出现错误并弄乱顺序或跳过一些索引。只需在提示中询问哪些图像的索引相似即可。截至目前，还无法为每张图片提供 ID，我认为这很遗憾，我希望尽快添加此功能。]]></description>
      <guid>https://community.openai.com/t/i-give-5-images-to-gpt4-vision-and-need-to-identify-2-similar-images/546521#post_8</guid>
      <pubDate>Wed, 03 Jan 2024 15:08:44 GMT</pubDate>
    </item>
    <item>
      <title>无需任何询问即可参与 ChatGPT</title>
      <link>https://community.openai.com/t/engage-with-chatgpt-without-any-inquiry/578181#post_1</link>
      <description><![CDATA[这不是编辑；这是一个实际问题。这个错误从去年开始就一直存在，并且仍然存在。它使 ChatGPT 能够在没有查询的情况下生成响应，有人知道它需要什么上下文来产生幻觉吗？

无查询幻觉消息：

要验证这一点，您需要首先发送查询消息，然后清除查询，最后发送空查询]]></description>
      <guid>https://community.openai.com/t/engage-with-chatgpt-without-any-inquiry/578181#post_1</guid>
      <pubDate>Wed, 03 Jan 2024 14:54:33 GMT</pubDate>
    </item>
    <item>
      <title>Whisper 偶尔不会开始转录/转录速度非常慢</title>
      <link>https://community.openai.com/t/whisper-occasionally-wont-start-transcribing-transcribes-very-slowly/576088#post_3</link>
      <description><![CDATA[@ruslana.koziienko
版主关闭此主题可以吗？]]></description>
      <guid>https://community.openai.com/t/whisper-occasionally-wont-start-transcribing-transcribes-very-slowly/576088#post_3</guid>
      <pubDate>Wed, 03 Jan 2024 14:48:11 GMT</pubDate>
    </item>
    <item>
      <title>助手——文本对象上的注释数组不一致</title>
      <link>https://community.openai.com/t/assistants-annotations-array-on-text-object-inconsistent/578179#post_1</link>
      <description><![CDATA[注释数组让我感到困惑。
我原本期望用可点击的视图注释按钮替换【16†source】样式的文本，但奇怪的是，有时注释要求文本如此随机地放置在段落中间？例如，请参见下面...作为被引用的部分，这有何意义？比如注释中的“range of se”有什么上下文吗？
{
“类型”：“文件引用”，
“text”：“se的范围”，
“start_index”：1284，
“end_index”：1295，
“文件引用”：{
“file_id”：“文件-CqE2HWvOspEpNiBloylXEGiZ”，
“quote”: “# 【3†uasession.docx†file-CqE2HWvOspEpNiBloylXEGiZ】\n第 3 组–ADMIN \t 194.\t 行善\t 第 3 组–ADMIN \t 195.\t 观察报告质疑倡导支持\t第 3 组 - 管理员 \t 196.\t 留意周围环境并为那些可能需要帮助的人挺身而出。\t 第 3 组 - 管理员 \t 197.\t 看到什么说些什么\t 第 3 组 - 管理员 \t 198 .\t 倡导学生安全及其根据事件和世代而变化的方式\t 第 3 组 - 管理员 \t 199。\t 如果我的同事似乎需要朋友，请在他们身边\t 第 3 组 - 管理员 \t 200 .\t 了解紧急行动计划是什么\t 第 3 组 – 管理员 \t 201。\t 观察报告注意自身和他人的安全\t 第 3 组 – 管理员 \t 202。\t 发展\t 第 3 组– ADMIN \t 203.\t 监听来自 UAPD UAlert\t Group 3 – ADMIN \t 204 的通信。”
}]]></description>
      <guid>https://community.openai.com/t/assistants-annotations-array-on-text-object-inconsistent/578179#post_1</guid>
      <pubDate>Wed, 03 Jan 2024 14:47:53 GMT</pubDate>
    </item>
    <item>
      <title>Whisper 偶尔不会开始转录/转录速度非常慢</title>
      <link>https://community.openai.com/t/whisper-occasionally-wont-start-transcribing-transcribes-very-slowly/576088#post_2</link>
      <description><![CDATA[关闭“CUDA Sysmem Fallback”解决了该问题。]]></description>
      <guid>https://community.openai.com/t/whisper-occasionally-wont-start-transcribing-transcribes-very-slowly/576088#post_2</guid>
      <pubDate>Wed, 03 Jan 2024 14:44:20 GMT</pubDate>
    </item>
    <item>
      <title>Gpt-4-1106-preview: 400 该模型的最大上下文长度为 4097 个标记</title>
      <link>https://community.openai.com/t/gpt-4-1106-preview-400-this-models-maximum-context-length-is-4097-tokens/578172#post_3</link>
      <description><![CDATA[我刚刚向 OP 添加了一些代码。通常我没有指定 max_tokens。
我希望我的后端能够接受长请求。
你知道gpt-4-1106-preview可以接受的最大上下文长度是多少吗？]]></description>
      <guid>https://community.openai.com/t/gpt-4-1106-preview-400-this-models-maximum-context-length-is-4097-tokens/578172#post_3</guid>
      <pubDate>Wed, 03 Jan 2024 14:38:52 GMT</pubDate>
    </item>
    <item>
      <title>无法访问高级数据分析</title>
      <link>https://community.openai.com/t/unable-to-access-advanced-data-analysis/392125#post_14</link>
      <description><![CDATA[我不确定“数据分析”（应该是探索版中的 GPT 之一）是否与 Beta 功能中的“高级数据分析”相同。通过此链接： https://help .openai.com/en/articles/8437071-advanced-data-analysis-chatgpt-enterprise-version，我知道Code Interpreter被更名为Advanced Data Analysis。我不知道“高级数据分析”选项是否已从所有 ChatGPT Plus 订阅的设置中的 Beta 功能中删除，这是我很想知道的事情。]]></description>
      <guid>https://community.openai.com/t/unable-to-access-advanced-data-analysis/392125#post_14</guid>
      <pubDate>Wed, 03 Jan 2024 14:36:08 GMT</pubDate>
    </item>
    <item>
      <title>导入 OpenAI“从打开导入 OpenAI”时出错</title>
      <link>https://community.openai.com/t/error-while-importing-openai-from-open-import-openai/578166#post_7</link>
      <description><![CDATA[已将错误传递给 ChatGPT，其中指出：
pip 卸载 Typing_extensions
pip 安装typing_extensions
]]></description>
      <guid>https://community.openai.com/t/error-while-importing-openai-from-open-import-openai/578166#post_7</guid>
      <pubDate>Wed, 03 Jan 2024 14:34:34 GMT</pubDate>
    </item>
    <item>
      <title>导入 OpenAI“从打开导入 OpenAI”时出错</title>
      <link>https://community.openai.com/t/error-while-importing-openai-from-open-import-openai/578166#post_6</link>
      <description><![CDATA[在这条消息的标题中，我写的是 import 而不是 import。
但在我的代码中我确实写了“from openai import OpenAI”。正如我所说，即使使用“import openai”，我也会遇到同样的错误。
清楚了吗？]]></description>
      <guid>https://community.openai.com/t/error-while-importing-openai-from-open-import-openai/578166#post_6</guid>
      <pubDate>Wed, 03 Jan 2024 14:29:25 GMT</pubDate>
    </item>
    <item>
      <title>Gpt-4-1106-preview: 400 该模型的最大上下文长度为 4097 个标记</title>
      <link>https://community.openai.com/t/gpt-4-1106-preview-400-this-models-maximum-context-length-is-4097-tokens/578172#post_2</link>
      <description><![CDATA[如果您确实指定了正确的 AI 模型，则可能是由于指定了错误的参数值而引发了不正确的错误消息。
我会首先查看您正在使用的max_tokens。这是令牌中的响应长度保留。它并没有告诉人工智能它自己的上下文窗口。
一个好的最大值约为 1500 个令牌，这是您从模型中获得的最多数量，除非执行特定的数据处理任务。
该AI模型可设置的最大输出为4k。]]></description>
      <guid>https://community.openai.com/t/gpt-4-1106-preview-400-this-models-maximum-context-length-is-4097-tokens/578172#post_2</guid>
      <pubDate>Wed, 03 Jan 2024 14:27:19 GMT</pubDate>
    </item>
    <item>
      <title>导入 OpenAI“从打开导入 OpenAI”时出错</title>
      <link>https://community.openai.com/t/error-while-importing-openai-from-open-import-openai/578166#post_5</link>
      <description><![CDATA[


 hndup0908：
&lt;块引用&gt;
“从开放导入 OpenAI”


这是拼写错误还是错误？]]></description>
      <guid>https://community.openai.com/t/error-while-importing-openai-from-open-import-openai/578166#post_5</guid>
      <pubDate>Wed, 03 Jan 2024 14:27:18 GMT</pubDate>
    </item>
    <item>
      <title>导入 OpenAI“从打开导入 OpenAI”时出错</title>
      <link>https://community.openai.com/t/error-while-importing-openai-from-open-import-openai/578166#post_4</link>
      <description><![CDATA[我修改了标题。
即使使用简单的 import openai ==&gt;我也有同样的错误。]]></description>
      <guid>https://community.openai.com/t/error-while-importing-openai-from-open-import-openai/578166#post_4</guid>
      <pubDate>Wed, 03 Jan 2024 14:26:31 GMT</pubDate>
    </item>
    </channel>
</rss>